### ISSUE TITLE
Can GHPRB detect when a commit is no longer on a PR?

### ISSUE THREAD

**Issue by jsquyres** [jenkinsci/ghprb-plugin#110]
Here's a scenario that has happened a few times:
1. Author creates a PR with a chain of commits
2. GHPRB kicks off a Jenkins job 1
3. Author rebases and force-pushes a new chain of commits, completely replacing the first chain of commits
4. GHPRB queues up Jenkins job 2 (because the first one is still running)
5. Author rebases and force-pushes _again_, and completely replaces the first chain of commits a 2nd time
6. GHPRB queues up Jenkins job 3 (because the first one is still running)

Of the two queued jobs, job 2 is now useless because the commits it will test are now no longer on the pull request (Jenkins job 1 is also useless, but there's not much we can do about that).

Is there a way to get GHPRB to check when it starts a new job to ensure that the commits it is testing are still associated with the pull request?

This would mean that Jenkins job 2 would be very quick, because GHPRB would realize that the commits it would have tested are no longer associated with the pull request, and GHPRB can skip the build.  Jenkins job 3 would also do the same check, realize that the commits _are_ still part of the pull request, and then continue to run the job.

**Comment by DavidTanner** [comment]
There are three phases where this plugin is interacting.  
1. When the trigger is run or the webhook is triggered.
2. When the build actually starts.
3. When the build finishes.

Your check would be going in when the build starts, to validate that the PR hasn't changed.  Unfortunately right now this would be somewhat hard to determine.

Because the build may or may not be using the actual commit, the plugin can't just choose to quit if it no longer matches.  The reference to the build also isn't retained once it is scheduled so this would require another change to the plugin. 

You are welcome to submit a pull request, or make some more suggestions here and I will get to them in time.

**Comment by jsquyres** [comment]
Ah, are you saying that in my above scenario:

1. Dev creates PR with commit chain 1
1. GHPRB kicks off job 1 on commit chain 1
1. Dev rebases / force-pushes PR with commit chain 2
1. GHPRB queues up job 2
1. Dev rebases / force-pushes PR with commit chain 3
1. GHPRB queues up job 3
1. Job 1 finally finishes, job 2 starts up

I guess I was assuming that job 2 would test commit chain 2 -- are you saying that job 2 will actually test commit chain 3?

**Comment by DavidTanner** [comment]
Yes.  Since the sha1 value is just "origin/pr/" + cause.getPullID() + "/merge" if the PR can be merged, it isn't tied to anything until the git client executes to check out the ref.  If you use ghprbActualCommit then it is tied to a commit sha that may/may not exist.

**Comment by jsquyres** [comment]
Ok.  That's probably a bit beyond my Jenkins-foo at the moment.  I guess this is best considered a minor optimization -- if someone codes it up someday, that would be great.  But it won't be the end of the world if no one does.  :smiley:

**Comment by bjoernhaeuser** [comment]
I just cleaning up some old issues, if this issue is still relevant please reopen.
