### ISSUE TITLE
trigger based on GitHub label

### ISSUE THREAD

**Issue by ixdy** [jenkinsci/ghprb-plugin#210]
As the summary states: it'd be nice to be able to trigger builds only when a pull request has a particular label added. (This is less noisy than making a comment.)

**Comment by benpatterson** [comment]
Noting here that this github webhooks do include events related to labels.

**Comment by IanVS** [comment]
Are you sure about that, @benpatterson?  GitHub's [api docs](https://developer.github.com/v3/activity/events/types/#pullrequestevent) say that a pull_request event is sent on labeling and unlabeling, and in fact that is the behavior I see when I test.

For example, I'm seeing:

```
{ 
    "action": "labeled",
    ...
    "label": {
        "id": 65342042,
        "url": "https://api.github.com/repos/xxxxx",
        "name": "CI",
        "color": "006b75",
        "default": false
     },
    ...
}
```

However, to be really effective, I would think that Jenkins would also need to be able to remove the label when the test is finished, so that it can be re-added to kick off another build.  Otherwise we would need to remove/readd the label to kick Jenkins (which isn't the end of the world either I suppose).

**Comment by benpatterson** [comment]
@IanVS I was saying what you are saying: that events are sent when something is labeled. Sorry if I'm missing something here...

**Comment by IanVS** [comment]
Ah, sorry, in my mind I added a `not` between `do` and `include`  🙄 

This would be a great feature to have.  Any idea how much effort it would be to implement?

**Comment by benpatterson** [comment]
Haha no problem @IanVS 

It's hard for me to tell you how much effort it would take. We recently merged a blacklist for labels, so I'm optimistic some of that can be re-used. But the true juggernaut right now is resolving issue 352; that is holding up other work on my end. If you were to take this on yourself I'd be glad to review/merge when ready.

**Comment by jamgood96** [comment]
I'm curious if there is any update to this or if anyone has found a work-around or possibly another plugin that will trigger builds based on label changes?

**Comment by jamesgoodhouse** [comment]
I'm curious if there is an update for this, or if anyone has found a work-around or possibly another plugin that allows building of pull requests upon changes to the labels?

**Comment by bjoernhaeuser** [comment]
This will be done by #639, therefore closing this for now.
