### ISSUE TITLE
Can't use SSH key as authentication mechanism

### ISSUE THREAD

**Issue by wesbland** [jenkinsci/ghprb-plugin#432]
When setting up the plugin in the main configuration page, there is no option to use an SSH key as the mechanism for authentication. This can actually be pretty important when using GitHub Enterprise and paying for per-seat licenses.

**Comment by junior-ales** [comment]
this is the main reason I'm not using this plugin in my workplace (Github Enterprise + SSH key auth)

**Comment by claudio-walser** [comment]
Well i think since you have to open a pull request with http requests on api.github.com, it's technically not even possible to use ssh keys. Except opening a pull request would bi implemented in git itself...
But at least this plugin should work with 2fa enabled and a configured access tokens. 
Therefore i opened this ticket: https://github.com/jenkinsci/ghprb-plugin/issues/458

**Comment by bjoernhaeuser** [comment]
The API needs an access token. Therefore this cannot work as far as I can see.

If you think otherwise please reopen the issue.
