### ISSUE TITLE
Results of multiple jenkins jobs overwrite status on Github PR

### ISSUE THREAD

**Issue by mareknovotny** [jenkinsci/ghprb-plugin#463]
Hi, I found this issue on original repository https://github.com/janinko/ghprb/issues/435

I tried to use Post build step to update status for every build with the job name, but it still works as the latest job overwrites the previous status (so first job1 fails and second job2 passes the only result of check is show as Passed).
Any idea how to configure Github PR builder to not overwrite the status check, but add all results?

**Comment by mareknovotny** [comment]
hmm, I found https://github.com/jenkinsci/ghprb-plugin/issues/208 and that led me to the Trigger setup and there to set a Context, which works as I wanted - adds a line for every job triggered by the PR.

**Comment by benpatterson** [comment]
@mareknovotny Glad you were able to sort this out.

Could you suggest some doc improvements? It'd be good to clear this up for other folks. Happy to update README.

**Comment by Lenerenberg** [comment]
@benpatterson Re: docs, Just make it clear that multiple checks need to have a different value for Context or else they will overwrite each other

**Comment by ksemaev** [comment]
@Lenerenberg what are those context values? Where are you getting them from?

**Comment by Lenerenberg** [comment]
@ksemaev I am providing that context value in the api call like : 
curl -XPOST https://api.github.com/repos/{repo_path}/statuses/$(git rev-parse HEAD) -d "{ \"context\": \"continuous-integration/jenkins\"}" --header "Content-Type: application/json"

I just didn't realize right away that multiple checks on the same commit would get overwritten unless a different value was provided for context on each.

**Comment by akomakom** [comment]
In case it helps someone, when using the GitHub Branch Source, you need to install the **GitHub SCM Trait Notification Context** plugin in order to be able to change the context for each job to make the checks unique:

https://plugins.jenkins.io/github-scm-trait-notification-context/

Then you can "Add" a "Behavior" of type "Custom Github Notification Context".  In my case, I'm using 2 Multibranch hierarchies for the same GitHub Org (because Jenkins can't handle multiple Jenkinsfiles per repo), and I needed the 2 checks to be unique.

**Comment by kmaladkar** [comment]
@akomakom Do you know if I can do the same thing on a single branch pipeline? and I can't find "Custom Github Notification Context" under "Add", do you know where I can find it?
