### ISSUE TITLE
Build getting triggered on old comments

### ISSUE THREAD

**Issue by bhumikagoyal** [jenkinsci/ghprb-plugin#518]
I enabled "Only use trigger phrase for build triggering" and everything works fine. But one thing I would like to suggest is that if I comment the trigger phrase, the build runs but if I close the PR and reopen it again then again the build runs because my trigger phrase is already there in the comment. So, it would be better that a comment should trigger the build only once and not every time a PR is reopened.
![selection_035](https://cloud.githubusercontent.com/assets/6457715/25798827/49b360ee-3400-11e7-86c0-bbf09a136a3d.png)

Here I commented the trigger 5 mins ago and the build ran. But after sometime I closed and reopened the PR and the build ran again which is not expected as the build should be triggered on a fresh comment and not on the past comments.

**Comment by bjoernhaeuser** [comment]
Not really. The comment is there telling jenkins to test. Why should it matter if you close the PR in the meantime? 

I am going to close this for now, if you have objections against it, please comment, I am happy to discuss this further.

**Comment by AdamBrousseau** [comment]
We've experienced this as well. Reopening a PR that was previously tested re-triggers the build. The problem for us is that the new build has parameter `ghprbCommentBody` equal to the last comment in the PR and we parse the trigger comment for build inputs. Since the last comment is not necessarily the trigger comment, our build errors out because the comment is not what our build is expecting. If there could be an option added like "re-trigger on reopen" that would solve this for us.
