### ISSUE TITLE
Problem in conjunction with configuration history plugin

### ISSUE THREAD

**Issue by christofdamian** [jenkinsci/ghprb-plugin#88]
I am using https://wiki.jenkins-ci.org/display/JENKINS/JobConfigHistory+Plugin and together with ghprb it seems to generate a backup of the ghprb configuration on every pull request. With 1.2M each this quickly generated 19GB of data on our installation at cloudbees. 
I am not sure what makes ghprb different from other plugins in this respect.

**Comment by KostyaSha** [comment]
Jenkins core and ghprb code design makes this. Jenkins store data in deseralised xmls and JobConfigHistory just saving any changes, that are constant in current ghprb plugin.

**Comment by christofdamian** [comment]
For now I removed JobConfigHistory, because I can't live without ghprb

**Comment by benpatterson** [comment]
Hi @christofdamian We also use both the ghprb plugin and the jobHistory plugin. We encountered this problem, because it was making a significant dent in our disk usage.

We got around it by putting a pattern in the master configuration. Specifically, we went to Manage Jenkins > Configure > JobConfigHistory > Advanced, and put a pattern in the "System configuration exclude file pattern" field. 

I honestly don't remember if there were any pre-filled values in that field, but here's our entire field as an FYI:  `queue|nodeMonitors|UpdateCenter|global-build-stats|GhprbTrigger`. I don't remember if it was pre-filled when we adjusted it...but you can see the last pipe handles this plugin. A couple of the others there were also taking up unnecessary space (at least, for us).

**Comment by christofdamian** [comment]
thanks @benpatterson ! I'll try that, sounds like a good and easy solution.

**Comment by bjoernhaeuser** [comment]
@christofdamian are you interested in providing a documentation update for this issue?

**Comment by bjoernhaeuser** [comment]
For now i am closing this issue.
